### ISSUE TITLE
Triggering / sending react-email templates from server side

### ISSUE THREAD

**Issue by riccardolardi** [anfragment/react-email-dynamic#1]
Hi there, referencing the issue in react-email: https://github.com/resend/react-email/discussions/570#discussioncomment-10580756

My use case is a Next.js application from which I need to send emails triggered by an external cronjob scheduler (using https://github.com/kelektiv/node-cron) and nodemailer. I would love to be able to build the emails using react-email for its ergonomics. But my understanding is that those emails JSX would need to be pre-compiled into static HTML if needed to be sent out by nodemailer, from outside Next.js.

This is the way I would like to send emails. The code resides in the Next.js codebase but is called from node-cron and therefore bypasses JSX compilation:

```ts
// src/lib/email/index.ts
import type { Locale } from "-/src/i18n";
import type { Post, Profile } from "@prisma/client";
import { convert as convertToText } from "html-to-text";
import { sendNodemailerEmail } from "./nodemailer";
import emailTemplate, { type EmailTemplateType } from "./templates";

async function sendEmailTemplate({
  type,
  post,
  recipientProfile,
}: {
  type: EmailTemplateType;
  post?: Partial<Post>;
  recipientProfile: Profile;
}) {
  const { template, subject } = await emailTemplate({
    type,
    locale: recipientProfile.locale.toLowerCase() as Locale,
  });
  const html = template({ post, recipientProfile });

  return await sendNodemailerEmail({
    to: recipientProfile.email,
    subject,
    text: convertToText(html),
    html,
  });
}

export { sendEmailTemplate };
```

Is there a better / more correct approach to this? Thanks a lot.

**Comment by anfragment** [comment]
Hello @riccardolardi! Honestly, it's as good as anything if it solves the problem for you.

> my understanding is that those emails JSX would need to be pre-compiled into static HTML

Yes, you can only use react-email-dynamic if you're passing a static string, as shown [here](https://github.com/anfragment/react-email-dynamic?tab=readme-ov-file#usage). This library was initially designed for use in a backend environment where we wanted to store templates in a database. I doubt that it's a good fit if you only need to send a limited number of static emails.

If you prefer writing your templates in JSX/react-email, I think [this](https://react.email/docs/utilities/render) might be a good fit for you. It allows rendering React components which Next.js should allow you to use on the backend.

**Comment by riccardolardi** [comment]
Hi @anfragment thanks so much for your help.

I think react-email's `render` only works when called from within a JSX environment - but I need to call it from simple .ts file since it's gonna be triggered from node-cron...

**Comment by anfragment** [comment]
Check out https://www.typescriptlang.org/tsconfig/#jsx. Your project environment is probably already configured to allow importing JSX from anywhere, otherwise it is still pretty easy to make it work.
